# Generated by Django 5.2.11 on 2026-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
