# Generated by Django 5.2.11 on 2026-06-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_match_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='detail_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='match',
            name='details_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='footlive_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='ht_away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ht_home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('goal', 'But'), ('own_goal', 'But contre son camp'), ('penalty', 'Penalty'), ('yellow_card', 'Carton jaune'), ('red_card', 'Carton rouge'), ('substitution', 'Remplacement')], max_length=20)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('player', models.CharField(max_length=120)),
                ('player_out', models.CharField(blank=True, max_length=120)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sports.match')),
            ],
            options={
                'ordering': ['minute', 'id'],
                'indexes': [models.Index(fields=['match', 'minute'], name='sports_matc_match_i_976c16_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('role', models.CharField(choices=[('starter', 'Titulaire'), ('substitute', 'Remplaçant')], max_length=12)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('player', models.CharField(max_length=120)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='sports.match')),
            ],
            options={
                'ordering': ['team_side', 'role', 'id'],
                'indexes': [models.Index(fields=['match', 'team_side', 'role'], name='sports_matc_match_i_48c1d5_idx')],
            },
        ),
    ]
