# Generated by Django 5.2.11 on 2026-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0005_team_unique_competition_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
