# Generated by Django 5.2.11 on 2026-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0006_team_logo_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="color_primary",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="team",
            name="color_secondary",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
