# Generated by Django 5.2.11 on 2026-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField(null=True, unique=True)),
                ('competition', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_team_crest', models.URLField(blank=True, max_length=500, null=True)),
                ('away_team_crest', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
