# Generated by Django 5.2.11 on 2026-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_crest',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_crest',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
