# Generated by Django 5.2.11 on 2026-05-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.CharField(choices=[('L1', 'Ligue 1'), ('UCL', 'Champions League'), ('PL', 'Premier League'), ('LIGA', 'La Liga'), ('BUN', 'Bundesliga'), ('SA', 'Serie A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('soon', 'À venir'), ('live', 'En direct'), ('finished', 'Terminé')], default='soon', max_length=20),
        ),
        migrations.AlterField(
            model_name='standing',
            name='competition',
            field=models.CharField(choices=[('L1', 'Ligue 1'), ('UCL', 'Champions League'), ('PL', 'Premier League'), ('LIGA', 'La Liga'), ('BUN', 'Bundesliga'), ('SA', 'Serie A')], max_length=10),
        ),
    ]
