# Generated by Django 5.2.11 on 2026-03-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_team_crest_match_home_team_crest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team_crest',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_crest',
        ),
    ]
