# Generated by Django 5.2.11 on 2026-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_away_team_crest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_crest',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_crest',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
