# Generated by Django 5.2.11 on 2026-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
