# Generated by Django 5.2.11 on 2026-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
