# Generated by Django 5.2.11 on 2026-05-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='odd_value',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='potential_win',
        ),
    ]
