# Generated by Django 5.2.11 on 2026-05-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_bet_odd_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
