# Generated by Django 5.2.11 on 2026-06-03 14:01

import django.db.models.deletion
from django.db import migrations, models


def backfill_selections(apps, schema_editor):
    """Crée une jambe (BetSelection) pour chaque pari existant à partir de ses
    anciennes colonnes match/odd, avant qu'elles soient supprimées."""
    Bet = apps.get_model("betting", "Bet")
    BetSelection = apps.get_model("betting", "BetSelection")
    for bet in Bet.objects.all():
        BetSelection.objects.create(
            bet=bet,
            match_id=bet.match_id,
            odd_id=bet.odd_id,
            odd_value=bet.odd_value,
            status=bet.status,
            settled_at=bet.settled_at,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_bet_created_at'),
        ('sports', '0002_alter_match_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='odd_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_selections', to='sports.match')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bet_selections', to='sports.odds')),
            ],
        ),
        migrations.RunPython(backfill_selections, noop),
        migrations.RemoveField(
            model_name='bet',
            name='match',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='odd',
        ),
    ]
